### ISSUE TITLE
Type issues with context and auth when upgrading cli from 8.0.0 to 8.0.1

### ISSUE THREAD

**Issue by Hoyby** [equinor/fusion-framework#1212]
**Describe the bug**
Seems to be a type issue with typing when upgrading fusion-framework-cli from [8.0.0](https://github.com/equinor/fusion-framework/blob/1b1a98a982323fe8384e8564e6229af7dc615839/packages/cli/CHANGELOG.md#800) to [8.0.1](https://github.com/equinor/fusion-framework/blob/1b1a98a982323fe8384e8564e6229af7dc615839/packages/cli/CHANGELOG.md#801) and [8.1.0](https://github.com/equinor/fusion-framework/blob/1b1a98a982323fe8384e8564e6229af7dc615839/packages/cli/CHANGELOG.md#810). 
The error goes away when manually downgrading the observable dependency from [8.1.0](https://github.com/equinor/fusion-framework/blob/1b1a98a982323fe8384e8564e6229af7dc615839/packages/utils/observable/CHANGELOG.md#810) to [8.0.3](https://github.com/equinor/fusion-framework/blob/1b1a98a982323fe8384e8564e6229af7dc615839/packages/utils/observable/CHANGELOG.md#803)

Related to the same cli upgrade I also get some issues with fetching the access token from window.Fusion.modules.auth. See stacktrace below.

**Environment**

- Windows
- Node Version: v18.12.1

**To Reproduce**
Copy the context cookbook code and upgrade fusion-framework-cli to 8.0.1 or 8.1.0

**Expected behavior**
No type error

**Stacktrace**

observable:
```
src/useRelatedContext.tsx:15:5 - error TS2322: Type 'ObservableStateReturnType<ContextItem<Record<string, unknown>>[] | undefined, unknown>' is not assignable to type 'ObservableStateReturnType<ContextItem[], unknown>'.
  Type 'ContextItem<Record<string, unknown>>[] | undefined' is not assignable to type 'ContextItem[]'.
    Type 'undefined' is not assignable to type 'ContextItem[]'.

15     return useObservableState(
       ~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  src/auth/getToken.ts:2
     1  src/useRelatedContext.tsx:15
Waiting for the debugger to disconnect...
error Command failed with exit code 2.
```

auth stacktrace:
```
src/auth/getToken.ts:2:47 - error TS2339: Property 'auth' does not exist on type 'never'.

2     const token = await window.Fusion.modules.auth.acquireAccessToken({ scopes });                                                ~~~~


Found 1 error in src/auth/getToken.ts:2
```

**Additional context**

**Comment by Hoyby** [comment]
Looks like `fusion-framework-react-app` 4.1.2 -> 4.1.4 gives the same error.

**Comment by Hoyby** [comment]
Just realized that we're not really using this function so It's no longer relevant for us.

**Comment by odinr** [comment]
only type-hint bug, not affected by build or IDE, only when executing `tsc -b` for our part
quick an easy fix
Code was made as an example of how to resolve a related context based on a selected context.
This is not a feature exposed by the framework, since implementation will vary for each use case

**Comment by odinr** [comment]
only type-hint bug, not affected by build or IDE, only when executing `tsc -b` for our part
quick an easy fix
Code was made as an example of how to resolve a related context based on a selected context.
This is not a feature exposed by the framework, since implementation will vary for each use case
